### ISSUE TITLE
感谢！非常好用！！！

### ISSUE THREAD

**Issue by wuxianlijiang** [Zws-China/wechat-Coordinate#3]
小程序定位获取的坐标，调用时偏移约500米，使用本工具‘transformFromWGSToGCJ’转换为火星坐标后，定位非常准确 。

**Comment by Lyfei** [comment]
怪不得这个不close

**Comment by penggang-home** [comment]
+1 
感谢！非常好用！！！
感谢！非常好用！！！
感谢！非常好用！！！

**Comment by Zws-China** [comment]
> 

你有毒，我close不close关你屁事

**Comment by Lyfei** [comment]
关就关呗，我又没要求你关，还喷人有毒干啥。。跳转进来你最后一条消息怎么没了
